[runtime]
log_level="INFO"

[destination.filesystem]
bucket_url = "gs://my_internal_bucket"

[data_writer]
buffer_max_items=1000


[load]
delete_completed_jobs=true

# set buffers in normalize stage
[normalize.data_writer]
buffer_max_items=1000
